import type { Metadata } from "next";
import { parseDeploySlug, buildDeployPath } from "@solcreek/og/deploy-url";

/**
 * Path-based deploy button entry point — server component.
 *
 * Canonical URL shapes:
 *
 *   creek.dev/deploy/gh/owner/repo                        → repo root
 *   creek.dev/deploy/gh/owner/repo/tree/main              → branch root
 *   creek.dev/deploy/gh/owner/repo/tree/main/apps/web     → subpath
 *
 *   (github / gitlab / bitbucket long forms and gl: / bb: shortcodes
 *    all accepted — see @solcreek/og/deploy-url for the full grammar.)
 *
 * This page:
 * 1. Exports generateMetadata() that fetches GitHub repo info server-side
 *    and returns repo-specific og:title / og:description / og:image so
 *    social crawlers (X / Twitter / Facebook / Discord / LinkedIn / Slack)
 *    show a per-repo preview card instead of the generic creek.dev card.
 * 2. Renders a minimal HTML shell that JS-redirects real users to the
 *    /new page where the actual deploy UI runs. Bots don't execute JS,
 *    so they only see the metadata. Humans get the interactive flow.
 *
 * URL parsing lives in @solcreek/og/deploy-url so this page and the
 * og-api worker share a single source of truth for which slugs are
 * valid and how tree/branch/subpath segments are interpreted.
 */

interface GitHubRepoMeta {
  name: string;
  full_name: string;
  description: string | null;
  stargazers_count: number;
  language: string | null;
  topics: string[];
  html_url: string;
  owner: { login: string; avatar_url: string };
}

/**
 * Fetch a GitHub repo's public metadata. Returns null for 404 / rate-limit
 * / network failure — the metadata functions fall back to generic copy in
 * that case rather than breaking the page render.
 */
async function fetchGitHubRepo(
  owner: string,
  repo: string,
): Promise<GitHubRepoMeta | null> {
  try {
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}`,
      {
        headers: {
          Accept: "application/vnd.github+json",
          "User-Agent": "creek-deploy-button",
        },
        // Next.js caches the response for 1 hour — repo metadata doesn't
        // change often and we don't want to hammer GitHub unauth limits.
        next: { revalidate: 3600 },
      },
    );
    if (!res.ok) return null;
    return (await res.json()) as GitHubRepoMeta;
  } catch {
    return null;
  }
}

export async function generateMetadata(
  { params }: { params: Promise<{ slug: string[] }> },
): Promise<Metadata> {
  const { slug } = await params;
  const parsed = parseDeploySlug(slug);

  if (!parsed) {
    return {
      title: "Deploy to Creek",
      description:
        "Deploy any GitHub repository to Creek in seconds — no signup, no config.",
    };
  }

  const { owner, repo, branch, subpath, provider } = parsed;

  // Only GitHub is wired for description fetch today.
  const meta = provider.host === "github.com"
    ? await fetchGitHubRepo(owner, repo)
    : null;

  // Title: for subpath, include the subpath as a colon suffix so users
  // can tell at a glance which part of the monorepo is being deployed.
  const repoLabel = subpath ? `${owner}/${repo}:${subpath}` : `${owner}/${repo}`;
  const title = `Deploy ${repoLabel} to Creek`;

  // Description: prefer GitHub repo description when present. Subpath
  // context goes in a parenthetical suffix.
  const baseDesc = meta?.description
    ? `${meta.description} — Deploy in ~15 seconds, no signup.`
    : `Deploy this ${provider.displayName} repo to Creek in ~15 seconds — no signup, no config, free sandbox URL.`;
  const description = subpath
    ? `${baseDesc} (Deploying from ${subpath})`
    : baseDesc;

  // Canonical URL mirrors the deploy URL grammar exactly.
  const deployPath = buildDeployPath(parsed);
  const canonical = `https://creek.dev/deploy/${deployPath}`;

  // Dynamic OG image generated by og-api. Path-based, includes subpath
  // so every variant renders its own card (and gets its own edge cache).
  const ogImage = `https://og.creek.dev/deploy/${deployPath}`;

  const altText = subpath
    ? `Deploy ${owner}/${repo} (${branch} / ${subpath}) to Creek`
    : `Deploy ${owner}/${repo} to Creek`;

  return {
    title,
    description,
    alternates: { canonical },
    openGraph: {
      type: "website",
      url: canonical,
      siteName: "Creek",
      title,
      description,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: altText,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      site: "@useCreek",
      title,
      description,
      images: [ogImage],
    },
  };
}

export default async function DeployPathPage(
  { params }: { params: Promise<{ slug: string[] }> },
) {
  const { slug } = await params;
  const parsed = parseDeploySlug(slug);

  // Invalid slug → static explainer (no redirect so bots still get metadata)
  if (!parsed) {
    return (
      <FallbackShell
        title="Deploy to Creek"
        subtitle="Paste a GitHub, GitLab, or Bitbucket repo URL to deploy it."
        ctaHref="/new"
        ctaLabel="Open Creek Deploy"
      />
    );
  }

  const { owner, repo, branch, subpath, provider } = parsed;

  // Build the full "GitHub tree" URL the user would copy-paste — this
  // is what we hand to /new via the ?repo= param. The /new page parses
  // owner/repo out of it and respects branch + path overrides via the
  // explicit ?branch= and ?path= query params below.
  const fullRepoUrl = subpath
    ? `https://${provider.host}/${owner}/${repo}/tree/${branch}/${subpath}`
    : branch
      ? `https://${provider.host}/${owner}/${repo}/tree/${branch}`
      : `https://${provider.host}/${owner}/${repo}`;

  const newParams = new URLSearchParams({ repo: fullRepoUrl });
  if (branch) newParams.set("branch", branch);
  if (subpath) newParams.set("path", subpath);
  const target = `/new?${newParams.toString()}`;

  const visualLabel = subpath ? `${owner}/${repo}:${subpath}` : `${owner}/${repo}`;

  // Render a minimal SSR shell with metadata-ready HTML. The <script> kicks
  // real users to the full /new page where useWebDeploy runs. Crawlers
  // don't execute JS, so they read metadata + snapshot this page and move
  // on — the metadata export above is what powers the social card.
  return (
    <FallbackShell
      title={`Deploy ${visualLabel}`}
      subtitle="One click → live URL in ~15 seconds. No signup."
      ctaHref={target}
      ctaLabel="Continue to deploy"
      redirectScriptTarget={target}
    />
  );
}

function FallbackShell({
  title,
  subtitle,
  ctaHref,
  ctaLabel,
  redirectScriptTarget,
}: {
  title: string;
  subtitle: string;
  ctaHref: string;
  ctaLabel: string;
  redirectScriptTarget?: string;
}) {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-[#e5e5e5] flex flex-col">
      <nav className="border-b border-[#222] bg-[#0a0a0a]/80 backdrop-blur-lg">
        <div className="mx-auto max-w-2xl flex items-center justify-between px-6 h-14">
          <a href="/" className="inline-flex items-baseline gap-1.5 text-base font-medium tracking-tight">
            <span aria-hidden="true">⬡</span>
            <span className="font-brand">Creek</span>
          </a>
          <div className="flex items-center gap-6 text-sm text-[#888]">
            <a href="/docs" className="hover:text-[#e5e5e5] transition-colors">Docs</a>
            <a href="/pricing" className="hover:text-[#e5e5e5] transition-colors">Pricing</a>
          </div>
        </div>
      </nav>

      <main className="flex-1 flex items-center justify-center px-6">
        <div className="max-w-md w-full text-center">
          <p className="text-xs font-mono text-[#888] mb-2">Deploy to Creek</p>
          <h1 className="text-2xl font-semibold tracking-tight mb-3">{title}</h1>
          <p className="text-sm text-[#888] mb-8 leading-relaxed">{subtitle}</p>
          <a
            href={ctaHref}
            className="inline-block py-3 px-8 rounded-xl bg-[#38bdf8] text-[#0a0a0a] font-semibold text-sm hover:bg-[#60d0e0] transition-colors"
          >
            {ctaLabel} →
          </a>
          <p className="mt-6 text-xs text-[#555]">
            No account needed — deploys to a 60-minute preview URL.
          </p>
        </div>
      </main>

      {redirectScriptTarget && (
        /* Real users in browsers get redirected immediately via JS.
           Crawlers (Twitterbot, facebookexternalhit, Slackbot, Discordbot,
           LinkedInBot) don't execute JS, so they stay on this page and
           read the openGraph metadata.
           IMPORTANT: do NOT add a <noscript><meta http-equiv="refresh"> —
           crawlers DO honour meta refresh, which would send them to /new
           (a client-rendered page with no per-repo metadata), breaking
           every social preview. The visible CTA link above is the
           accessibility fallback for any real no-JS user. */
        <script
          dangerouslySetInnerHTML={{
            __html: `window.location.replace(${JSON.stringify(redirectScriptTarget)});`,
          }}
        />
      )}
    </div>
  );
}
