#!/usr/bin/env bash
# Build the workspace CLI once and open an isolated run directory.
# Prints the path to run.env on the last line of stdout.
set -euo pipefail
# shellcheck disable=SC1091
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

need_cli=0
if [[ ! -f "$VERIFY_CREEK_CLI_DIST" || "${VERIFY_CREEK_FORCE_BUILD:-}" == "1" ]]; then
  need_cli=1
fi
if [[ ! -f "$VERIFY_CREEK_REPO/packages/sdk/dist/index.js" ]]; then
  echo "verify-creek: building @solcreek/sdk (CLI depends on it)" >&2
  pnpm --dir "$VERIFY_CREEK_REPO" --filter @solcreek/sdk build >&2
fi
if [[ "$need_cli" == "1" ]]; then
  echo "verify-creek: building @solcreek/cli" >&2
  pnpm --dir "$VERIFY_CREEK_REPO" --filter @solcreek/cli build >&2
fi
if [[ ! -f "$VERIFY_CREEK_CLI_DIST" ]]; then
  echo "verify-creek: CLI dist missing after build: $VERIFY_CREEK_CLI_DIST" >&2
  exit 1
fi
if [[ ! -f "$VERIFY_CREEK_BIN_DEFAULT" ]]; then
  echo "verify-creek: facade bin missing: $VERIFY_CREEK_BIN_DEFAULT" >&2
  exit 1
fi

run_id="${VERIFY_CREEK_RUN_ID:-$(date +%Y%m%dT%H%M%S)-$$}"
_tmp="${TMPDIR:-/tmp}"
_tmp="${_tmp%/}"
run_dir="${VERIFY_CREEK_RUN:-$_tmp/verify-creek-$run_id}"
mkdir -p "$run_dir/home" "$run_dir/work" "$run_dir/home/.creek"
env_file="$run_dir/run.env"

cat >"$env_file" <<EOF
# Generated by verify-creek launch.sh. Source from the other helpers only.
unset CREEK_TOKEN
export VERIFY_CREEK_RUN=$(printf '%q' "$run_dir")
export VERIFY_CREEK_HOME=$(printf '%q' "$run_dir/home")
export VERIFY_CREEK_WORK=$(printf '%q' "$run_dir/work")
export VERIFY_CREEK_BIN=$(printf '%q' "$VERIFY_CREEK_BIN_DEFAULT")
export VERIFY_CREEK_REPO=$(printf '%q' "$VERIFY_CREEK_REPO")
export HOME=$(printf '%q' "$run_dir/home")
export CREEK_API_URL=$(printf '%q' "$VERIFY_CREEK_DEAD_API")
export CREEK_SANDBOX_API_URL=$(printf '%q' "$VERIFY_CREEK_DEAD_API")
export CREEK_HOSTS_PATH=$(printf '%q' "$run_dir/home/.creek/hosts.json")
EOF

echo "verify-creek: isolated HOME=$run_dir/home" >&2
echo "verify-creek: work dir     $run_dir/work" >&2
echo "verify-creek: binary       $VERIFY_CREEK_BIN_DEFAULT" >&2
echo "$env_file"
