import { describe, test, expect, afterEach } from "vitest";
import { generateWsToken, _setEnv } from "./index.js";

/**
 * Simulate the realtime-worker's verification logic.
 * This mirrors verifyWsToken in realtime-worker/src/index.ts.
 */
async function simulateVerify(
  masterKey: string,
  slug: string,
  token: string,
  maxAge = 300,
): Promise<boolean> {
  const dotIdx = token.indexOf(".");
  if (dotIdx === -1) return false;

  const timestampStr = token.slice(0, dotIdx);
  const hmacStr = token.slice(dotIdx + 1);
  const timestamp = parseInt(timestampStr, 10);
  if (isNaN(timestamp)) return false;

  const now = Math.floor(Date.now() / 1000);
  if (now - timestamp > maxAge) return false;

  // Derive per-project secret: HMAC(masterKey, slug)
  const masterCryptoKey = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(masterKey),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const projectSecretBuf = await crypto.subtle.sign(
    "HMAC",
    masterCryptoKey,
    new TextEncoder().encode(slug),
  );
  const projectSecret = Array.from(new Uint8Array(projectSecretBuf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

  // Verify: HMAC(projectSecret, "{slug}:ws:{timestamp}")
  const tokenKey = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(projectSecret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const expectedBuf = await crypto.subtle.sign(
    "HMAC",
    tokenKey,
    new TextEncoder().encode(`${slug}:ws:${timestamp}`),
  );
  const expected = Array.from(new Uint8Array(expectedBuf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

  if (expected.length !== hmacStr.length) return false;
  let mismatch = 0;
  for (let i = 0; i < expected.length; i++) {
    mismatch |= expected.charCodeAt(i) ^ hmacStr.charCodeAt(i);
  }
  return mismatch === 0;
}

// Simulate control-plane deriving per-project secret
async function deriveProjectSecret(masterKey: string, slug: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(masterKey),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(slug));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const MASTER_KEY = "test-master-key-for-unit-tests";
const SLUG = "my-project";

afterEach(() => {
  _setEnv(null as any);
});

describe("WS token: generate (runtime) + verify (realtime-worker)", () => {
  test("token generated by runtime passes realtime-worker verification", async () => {
    const projectSecret = await deriveProjectSecret(MASTER_KEY, SLUG);
    _setEnv({
      CREEK_REALTIME_SECRET: projectSecret,
      CREEK_PROJECT_SLUG: SLUG,
    });

    const token = await generateWsToken();
    expect(token).not.toBeNull();

    const valid = await simulateVerify(MASTER_KEY, SLUG, token!);
    expect(valid).toBe(true);
  });

  test("wrong master key fails verification", async () => {
    const projectSecret = await deriveProjectSecret(MASTER_KEY, SLUG);
    _setEnv({
      CREEK_REALTIME_SECRET: projectSecret,
      CREEK_PROJECT_SLUG: SLUG,
    });

    const token = await generateWsToken();
    const valid = await simulateVerify("wrong-master-key", SLUG, token!);
    expect(valid).toBe(false);
  });

  test("wrong slug fails verification", async () => {
    const projectSecret = await deriveProjectSecret(MASTER_KEY, SLUG);
    _setEnv({
      CREEK_REALTIME_SECRET: projectSecret,
      CREEK_PROJECT_SLUG: SLUG,
    });

    const token = await generateWsToken();
    const valid = await simulateVerify(MASTER_KEY, "wrong-slug", token!);
    expect(valid).toBe(false);
  });

  test("tampered token fails verification", async () => {
    const projectSecret = await deriveProjectSecret(MASTER_KEY, SLUG);
    _setEnv({
      CREEK_REALTIME_SECRET: projectSecret,
      CREEK_PROJECT_SLUG: SLUG,
    });

    const token = await generateWsToken();
    // Flip a character in the middle of the HMAC to guarantee difference
    const parts = token!.split(".");
    const hmac = parts[1];
    const mid = Math.floor(hmac.length / 2);
    const flipped = hmac[mid] === "a" ? "b" : "a";
    const tampered = parts[0] + "." + hmac.slice(0, mid) + flipped + hmac.slice(mid + 1);
    const valid = await simulateVerify(MASTER_KEY, SLUG, tampered);
    expect(valid).toBe(false);
  });

  test("expired token fails verification", async () => {
    const projectSecret = await deriveProjectSecret(MASTER_KEY, SLUG);
    _setEnv({
      CREEK_REALTIME_SECRET: projectSecret,
      CREEK_PROJECT_SLUG: SLUG,
    });

    // Manually create an expired token (10 minutes ago)
    const expiredTimestamp = Math.floor(Date.now() / 1000) - 600;
    const message = `${SLUG}:ws:${expiredTimestamp}`;
    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(projectSecret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"],
    );
    const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
    const hmac = Array.from(new Uint8Array(sig))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    const expiredToken = `${expiredTimestamp}.${hmac}`;

    const valid = await simulateVerify(MASTER_KEY, SLUG, expiredToken);
    expect(valid).toBe(false);
  });

  test("invalid format fails verification", async () => {
    expect(await simulateVerify(MASTER_KEY, SLUG, "not-a-token")).toBe(false);
    expect(await simulateVerify(MASTER_KEY, SLUG, "")).toBe(false);
    expect(await simulateVerify(MASTER_KEY, SLUG, "abc.def")).toBe(false);
  });
});
