/**
 * Worker entry source code generator.
 *
 * Generates a CF Workers entry that statically imports all Next.js
 * page/route handlers. With --webpack, .next/server/app/*.js are
 * standard CJS modules that esbuild can bundle.
 */

import type { NextAdapter } from "next";

type BuildContext = Parameters<NonNullable<NextAdapter["onBuildComplete"]>>[0];

export interface WorkerEntryOptions {
  buildId: string;
  routing: BuildContext["routing"];
  outputs: BuildContext["outputs"];
  basePath: string;
  /** Embedded manifests: absolute path → file content */
  manifests: Record<string, string>;
}

interface HandlerEntry {
  pathname: string;
  importPath: string;
  varName: string;
  runtime: "nodejs" | "edge";
  type: string;
}

/**
 * Generate the worker entry source code.
 * All handler modules are statically imported so esbuild bundles them.
 */
export function generateWorkerEntry(opts: WorkerEntryOptions): string {
  const handlers = collectHandlers(opts.outputs);
  const pathnames = collectPathnames(opts.outputs);

  // Lazy imports wrapped in try/catch — CF Workers crashes on module eval errors.
  const handlerEntries = handlers
    .map(
      (h) =>
        `  ${JSON.stringify(h.pathname)}: { load: () => import(${JSON.stringify(h.importPath)}), runtime: ${JSON.stringify(h.runtime)}, type: ${JSON.stringify(h.type)} },`,
    )
    .join("\n");

  // Collect client-reference-manifest JS files from build output.
  // These set globalThis.__RSC_MANIFEST[page] = { ... } which the
  // Next.js renderer needs for React Server Components.
  const manifestImports = collectManifestPaths(opts.outputs)
    .map((p) => `import ${JSON.stringify(p)};`)
    .join("\n");

  return `
// Generated by @solcreek/adapter-nextjs — do not edit
import { resolveRoutes } from "@next/routing";
import { DurableObject } from "cloudflare:workers";

// DO class stubs — required by control-plane for Next.js ISR bindings.
export class DOQueueHandler extends DurableObject {}
export class DOShardedTagCache extends DurableObject {}
export class BucketCachePurge extends DurableObject {}

const BUILD_ID = ${JSON.stringify(opts.buildId)};
const BASE_PATH = ${JSON.stringify(opts.basePath)};
const ROUTING = ${JSON.stringify(opts.routing)};
const PATHNAMES = ${JSON.stringify(pathnames)};

// Embedded manifests — Next.js route modules call loadManifest() which
// normally uses fs.readFileSync(). Expose on globalThis so the shim can access it.
globalThis.__MANIFESTS = ${JSON.stringify(opts.manifests)};

// Initialize manifests singleton — called lazily on first SSR request.
function __initManifests() {
  const MANIFESTS_SINGLETON = Symbol.for('next.server.manifests');
  if (globalThis[MANIFESTS_SINGLETON]) return;

  // Parse client-reference manifests from embedded data.
  // The JS files have format: globalThis.__RSC_MANIFEST=(...);globalThis.__RSC_MANIFEST["/page"]={...};
  // We extract the JSON object directly via regex instead of eval.
  globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {};
  const manifests = globalThis.__MANIFESTS || {};
  for (const [key, content] of Object.entries(manifests)) {
    if (!key.includes("client-reference-manifest.js")) continue;
    try {
      // Format: globalThis.__RSC_MANIFEST=(...);globalThis.__RSC_MANIFEST["/page"]={...};
      // Find the second assignment (the one with the page key)
      const idx = content.lastIndexOf('__RSC_MANIFEST[');
      if (idx >= 0) {
        // Extract page key between ["..."]
        const keyStart = content.indexOf('"', idx);
        const keyEnd = content.indexOf('"', keyStart + 1);
        const page = content.slice(keyStart + 1, keyEnd);
        // Extract JSON after ]=
        const jsonStart = content.indexOf(']=', keyEnd) + 2;
        let jsonStr = content.slice(jsonStart);
        if (jsonStr.endsWith(';')) jsonStr = jsonStr.slice(0, -1);
        globalThis.__RSC_MANIFEST[page] = JSON.parse(jsonStr);
      }
    } catch {}
  }

  {
    // Parse server-reference-manifest for server actions
    let serverActionsManifest = { encryptionKey: "", node: {}, edge: {} };
    try {
      const raw = globalThis.__MANIFESTS && Object.entries(globalThis.__MANIFESTS)
        .find(([k]) => k.includes("server-reference-manifest.json"));
      if (raw) serverActionsManifest = JSON.parse(raw[1]);
    } catch {}

    // Initialize with empty client reference map (pages will register via __RSC_MANIFEST)
    const clientReferenceManifestsPerRoute = new Map();
    const rscManifest = globalThis.__RSC_MANIFEST || {};
    for (const [page, manifest] of Object.entries(rscManifest)) {
      // __RSC_MANIFEST keys are like "/page", "/pricing/page", "/docs/[[...slug]]/page"
      // workStore.route uses "/", "/pricing", "/docs/[[...slug]]"
      const normalized = page.replace(/\\/page$/, "").replace(/^$/, "/");
      clientReferenceManifestsPerRoute.set(normalized, manifest);
      // Also keep the original key for direct lookups
      clientReferenceManifestsPerRoute.set(page, manifest);
    }

    // Create proxy for client references
    const proxiedClientReferenceManifest = new Proxy({}, {
      get(_, prop) {
        if (prop === "clientModules" || prop === "rscModuleMapping" || prop === "ssrModuleMapping" ||
            prop === "edgeRscModuleMapping" || prop === "edgeSSRModuleMapping") {
          return new Proxy({}, {
            get(__, id) {
              for (const manifest of clientReferenceManifestsPerRoute.values()) {
                if (manifest && manifest[prop] && manifest[prop][id]) return manifest[prop][id];
              }
              return undefined;
            }
          });
        }
        if (prop === "moduleLoading" || prop === "entryCSSFiles" || prop === "entryJSFiles") {
          const first = clientReferenceManifestsPerRoute.values().next().value;
          return first ? first[prop] : undefined;
        }
        return undefined;
      }
    });

    globalThis[MANIFESTS_SINGLETON] = {
      clientReferenceManifestsPerRoute,
      proxiedClientReferenceManifest,
      serverActionsManifest: {
        encryptionKey: serverActionsManifest.encryptionKey || "",
        node: Object.assign(Object.create(null), serverActionsManifest.node || {}),
        edge: Object.assign(Object.create(null), serverActionsManifest.edge || {}),
      },
      serverModuleMap: new Proxy({}, {
        get: (_, id) => {
          const workers = serverActionsManifest.node?.[id]?.workers;
          if (!workers) return undefined;
          const entry = Object.values(workers)[0];
          return entry ? { id: entry.moduleId, name: id, chunks: [], async: entry.async } : undefined;
        }
      }),
    };
  }
}


const HANDLERS = {
${handlerEntries}
};

// Middleware: Phase 1 passthrough
const middlewareHandler = async () => ({});

// --- Node.js bridge ---
${NODE_BRIDGE_CODE}

export default {
  async fetch(request, env, ctx) {
    try {
      __initManifests();
      const url = new URL(request.url);

      // 1. Static assets via WfP ASSETS binding
      if (url.pathname.startsWith("/_next/static/")) {
        return env.ASSETS.fetch(request);
      }

      // 2. Try serving as static asset
      try {
        const assetRes = await env.ASSETS.fetch(
          new Request(new URL(url.pathname, url.origin), { headers: request.headers })
        );
        if (assetRes.ok) return assetRes;
      } catch {}

      // 3. Route resolution via @next/routing
      const result = await resolveRoutes({
        url: new URL(request.url),
        buildId: BUILD_ID,
        basePath: BASE_PATH,
        headers: request.headers,
        requestBody: request.body,
        pathnames: PATHNAMES,
        routes: ROUTING,
        invokeMiddleware: middlewareHandler,
      });

      if (result.redirect) {
        return Response.redirect(result.redirect.url.toString(), result.redirect.status);
      }
      if (result.middlewareResponded) {
        return new Response(null, { status: 204 });
      }

      // 4. Invoke matched handler
      const resolvedPathname = result.resolvedPathname;
      if (!resolvedPathname || !HANDLERS[resolvedPathname]) {
        try {
          const notFound = await env.ASSETS.fetch(new Request(new URL("/404.html", url.origin)));
          return new Response(notFound.body, { status: 404, headers: notFound.headers });
        } catch {
          return new Response("Not Found", { status: 404 });
        }
      }

      const handler = HANDLERS[resolvedPathname];
      const mod = await handler.load();

      if (handler.runtime === "edge") {
        const fn = mod.default || mod.handler;
        if (typeof fn === "function") {
          return fn(request, { waitUntil: ctx.waitUntil.bind(ctx) });
        }
      }

      // Invoke handler with error capture via manual promise
      const { IncomingMessage: IM2, ServerResponse: SR2 } = await import("http");
      const nodeReq = new IM2();
      nodeReq.method = request.method;
      nodeReq.url = url.pathname + url.search;
      nodeReq.headers = Object.fromEntries(request.headers);
      nodeReq.push(null);

      const nodeRes = new SR2(nodeReq);
      const resChunks = [];
      nodeRes.on("data", (chunk) => {
        if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
        resChunks.push(chunk);
      });

      const responseReady = new Promise((resolve) => {
        nodeRes.on("finish", () => resolve("finish"));
        nodeRes.on("close", () => resolve("close"));
        setTimeout(() => resolve("timeout"), 25000);
      });

      const handlerFn = mod.handler;
      const handlerResult = handlerFn(nodeReq, nodeRes, {
        waitUntil: (p) => ctx.waitUntil(p.catch(() => {})),
        requestMeta: { relativeProjectDir: ".", hostname: request.headers.get("host") || "localhost" },
      });

      // Swallow the handler promise rejection to prevent 1101
      if (handlerResult?.then) {
        handlerResult.catch((err) => {
          if (!nodeRes.finished) {
            nodeRes.statusCode = 500;
            nodeRes.end(JSON.stringify({ error: "render_error", message: err instanceof Error ? err.message : String(err) }));
          }
        });
      }

      const reason = await responseReady;

      if (reason === "timeout" && resChunks.length === 0) {
        return new Response(JSON.stringify({ error: "ssr_timeout", message: "Handler did not respond within 25s" }), {
          status: 500, headers: { "Content-Type": "application/json" },
        });
      }

      const body = resChunks.length > 0 ? new Blob(resChunks).stream() : null;
      return new Response(body, {
        status: nodeRes.statusCode,
        headers: nodeRes.getHeaders(),
      });
    } catch (err) {
      const msg = err instanceof Error ? (err.stack || err.message) : String(err);
      return new Response(JSON.stringify({ error: "ssr_error", message: msg }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
};
`;
}

function collectHandlers(outputs: BuildContext["outputs"]): HandlerEntry[] {
  const handlers: HandlerEntry[] = [];
  const seen = new Set<string>();
  let idx = 0;

  const addOutput = (
    output: { pathname: string; filePath: string; runtime: "nodejs" | "edge" },
    type: string,
  ) => {
    if (output.pathname.endsWith(".rsc")) return;
    if (seen.has(output.pathname)) return;
    seen.add(output.pathname);

    handlers.push({
      pathname: output.pathname,
      importPath: output.filePath,
      varName: `_h${idx++}`,
      runtime: output.runtime,
      type,
    });
  };

  for (const page of outputs.appPages) addOutput(page, "APP_PAGE");
  for (const route of outputs.appRoutes) addOutput(route, "APP_ROUTE");
  for (const page of outputs.pages) addOutput(page, "PAGES");
  for (const api of outputs.pagesApi) addOutput(api, "PAGES_API");

  return handlers;
}

/**
 * Find client-reference-manifest JS files in the build output.
 * These are generated per-page in .next/server/app/<page>/page_client-reference-manifest.js
 * and set globalThis.__RSC_MANIFEST[page] when executed.
 */
function collectManifestPaths(outputs: BuildContext["outputs"]): string[] {
  const paths: string[] = [];
  const seen = new Set<string>();

  for (const page of outputs.appPages) {
    if (page.pathname.endsWith(".rsc")) continue;

    // The manifest file is next to the page handler:
    // .next/server/app/<page>/page.js → page_client-reference-manifest.js
    const dir = page.filePath.replace(/\/page\.js$/, "");
    const manifestPath = dir + "/page_client-reference-manifest.js";
    if (!seen.has(manifestPath)) {
      seen.add(manifestPath);
      paths.push(manifestPath);
    }
  }

  return paths;
}

function collectPathnames(outputs: BuildContext["outputs"]): string[] {
  const pathnames = new Set<string>();
  for (const p of outputs.appPages) pathnames.add(p.pathname);
  for (const r of outputs.appRoutes) pathnames.add(r.pathname);
  for (const p of outputs.pages) pathnames.add(p.pathname);
  for (const a of outputs.pagesApi) pathnames.add(a.pathname);
  for (const s of outputs.staticFiles) pathnames.add(s.pathname);
  return [...pathnames];
}

const NODE_BRIDGE_CODE = `
import { IncomingMessage, ServerResponse } from "http";

async function invokeNodeHandler(request, mod, ctx) {
  const url = new URL(request.url);

  // Create IncomingMessage from our shim (aliased from node:http)
  const req = new IncomingMessage();
  req.method = request.method;
  req.url = url.pathname + url.search;
  req.headers = Object.fromEntries(request.headers);
  // Push body
  if (request.body) {
    const reader = request.body.getReader();
    (async () => {
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) { req.push(null); break; }
          req.push(value);
        }
      } catch { req.push(null); }
    })();
  } else {
    req.push(null);
  }

  // Create ServerResponse from our shim
  const res = new ServerResponse(req);
  const chunks = [];
  let resolveResponse, rejectResponse;
  const responsePromise = new Promise((resolve, reject) => {
    resolveResponse = resolve;
    rejectResponse = reject;
  });

  // Capture written chunks
  const origWrite = res.write.bind(res);
  res.write = function(chunk, encoding, cb) {
    if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
    if (chunk) chunks.push(chunk);
    if (typeof encoding === "function") { cb = encoding; encoding = undefined; }
    if (cb) cb();
    return true;
  };

  const origEnd = res.end.bind(res);
  res.end = function(chunk, encoding, cb) {
    if (typeof chunk === "function") { cb = chunk; chunk = null; }
    if (typeof encoding === "function") { cb = encoding; encoding = null; }
    if (chunk) {
      if (typeof chunk === "string") chunk = new TextEncoder().encode(chunk);
      chunks.push(chunk);
    }
    res.finished = true;
    resolveResponse();
    if (cb) cb();
    return res;
  };

  // Invoke the handler
  const handlerFn = mod.handler || mod.routeModule?.handle?.bind(mod.routeModule) || mod.default;
  if (typeof handlerFn !== "function") {
    throw new Error("No handler function found");
  }

  try {
    const result = handlerFn(req, res, {
      waitUntil: ctx.waitUntil.bind(ctx),
      requestMeta: {
        relativeProjectDir: ".",
        hostname: request.headers.get("host") || "localhost",
      },
    });
    if (result?.then) await result;
  } catch (err) {
    if (!res.finished) {
      rejectResponse(err);
    }
  }

  // Wait for response with timeout
  await Promise.race([
    responsePromise,
    new Promise((_, reject) => setTimeout(() => reject(new Error("SSR timeout (25s)")), 25000)),
  ]);

  const body = chunks.length > 0 ? new Blob(chunks).stream() : null;
  return new Response(body, {
    status: res.statusCode,
    statusText: res.statusMessage,
    headers: res.getHeaders(),
  });
}
`;
